namespace:
  name: sandbox

image:
  repository: noelsharker/techtrends
  tag: latest
  imagePullPolicy: IfNotPresent

service:
  port: 4111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP

containerPort: 3111

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
    
replicaCount: 1