namespace:
  name: prod

image:
  imagePullPolicy: Always

service:
  port: 7111

resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"
    
replicaCount: 5